import { shuffleStyles } from '../lib/logic';

export const initialCast = [
  {
    id: 1,
    placement: 1,
    teamMembers: [
      {
        firstName: 'Xochitl',
        lastName: 'Gomez',
        image: '/pros/dani.jpeg',
        type: 'celeb',
        dataIndex: 0,
      },
      {
        firstName: 'Val',
        lastName: 'Chmerkovskiy',
        image: '/pros/dani.jpeg',
        type: 'pro',
        dataIndex: 14,
      },
    ],
    dances: [],
    styles: shuffleStyles().slice(),
  },
  {
    id: 2,
    placement: 2,
    teamMembers: [
      {
        firstName: 'Jason',
        lastName: 'Mraz',
        image: '/pros/dani.jpeg',
        type: 'celeb',
        dataIndex: 1,
      },
      {
        firstName: 'Daniella',
        lastName: 'Karagach',
        image: '/pros/dani.jpeg',
        type: 'pro',
        dataIndex: 4,
      },
    ],
    dances: [],
    styles: shuffleStyles().slice(),
  },
  {
    id: 3,
    placement: 3,
    teamMembers: [
      {
        firstName: 'Ariana',
        lastName: 'Madix',
        image: '/pros/dani.jpeg',
        type: 'celeb',
        dataIndex: 2,
      },
      {
        firstName: 'Pasha',
        lastName: 'Pashkov',
        image: '/pros/dani.jpeg',
        type: 'pro',
        dataIndex: 10,
      },
    ],
    dances: [],
    styles: shuffleStyles().slice(),
  },
  {
    id: 4,
    placement: 4,
    teamMembers: [
      {
        firstName: 'Charity',
        lastName: 'Lawson',
        image: '/pros/dani.jpeg',
        type: 'celeb',
        dataIndex: 3,
      },
      {
        firstName: 'Artem',
        lastName: 'Chigvintsev',
        image: '/pros/dani.jpeg',
        type: 'pro',
        dataIndex: 1,
      },
    ],
    dances: [],
    styles: shuffleStyles().slice(),
  },
  {
    id: 5,
    placement: 5,
    teamMembers: [
      {
        firstName: 'Alyson',
        lastName: 'Hannigan',
        image: '/pros/dani.jpeg',
        type: 'celeb',
        dataIndex: 4,
      },
      {
        firstName: 'Sasha',
        lastName: 'Farber',
        image: '/pros/dani.jpeg',
        type: 'pro',
        dataIndex: 13,
      },
    ],
    dances: [],
    styles: shuffleStyles().slice(),
  },
  {
    id: 6,
    placement: 6,
    teamMembers: [
      {
        firstName: 'Harry',
        lastName: 'Jowsey',
        image: '/pros/dani.jpeg',
        type: 'celeb',
        dataIndex: 5,
      },
      {
        firstName: 'Rylee',
        lastName: 'Arnold',
        image: '/pros/dani.jpeg',
        type: 'pro',
        dataIndex: 12,
      },
    ],
    dances: [],
    styles: shuffleStyles().slice(),
  },
  {
    id: 7,
    placement: 7,
    teamMembers: [
      {
        firstName: 'Barry',
        lastName: 'Williams',
        image: '/pros/dani.jpeg',
        type: 'celeb',
        dataIndex: 6,
      },
      {
        firstName: 'Peta',
        lastName: 'Murgatroyd',
        image: '/pros/dani.jpeg',
        type: 'pro',
        dataIndex: 11,
      },
    ],
    dances: [],
    styles: shuffleStyles().slice(),
  },
  {
    id: 8,
    placement: 8,
    teamMembers: [
      {
        firstName: 'Lele',
        lastName: 'Pons',
        image: '/pros/dani.jpeg',
        type: 'celeb',
        dataIndex: 7,
      },
      {
        firstName: 'Brandon',
        lastName: 'Armstrong',
        image: '/pros/dani.jpeg',
        type: 'pro',
        dataIndex: 2,
      },
    ],
    dances: [],
    styles: shuffleStyles().slice(),
  },
  {
    id: 9,
    placement: 9,
    teamMembers: [
      {
        firstName: 'Mauricio',
        lastName: 'Umansky',
        image: '/pros/dani.jpeg',
        type: 'celeb',
        dataIndex: 8,
      },
      {
        firstName: 'Emma',
        lastName: 'Slater',
        image: '/pros/dani.jpeg',
        type: 'pro',
        dataIndex: 5,
      },
    ],
    dances: [],
    styles: shuffleStyles().slice(),
  },
  {
    id: 10,
    placement: 10,
    teamMembers: [
      {
        firstName: 'Mira',
        lastName: 'Sorvino',
        image: '/pros/dani.jpeg',
        type: 'celeb',
        dataIndex: 9,
      },
      {
        firstName: 'Gleb',
        lastName: 'Savchenko',
        image: '/pros/dani.jpeg',
        type: 'pro',
        dataIndex: 7,
      },
    ],
    dances: [],
    styles: shuffleStyles().slice(),
  },
  {
    id: 11,
    placement: 11,
    teamMembers: [
      {
        firstName: 'Adrian',
        lastName: 'Peterson',
        image: '/pros/dani.jpeg',
        type: 'celeb',
        dataIndex: 10,
      },
      {
        firstName: 'Britt',
        lastName: 'Stewart',
        image: '/pros/dani.jpeg',
        type: 'pro',
        dataIndex: 3,
      },
    ],
    dances: [],
    styles: shuffleStyles().slice(),
  },
  {
    id: 12,
    placement: 12,
    teamMembers: [
      {
        firstName: 'Tyson',
        lastName: 'Beckford',
        image: '/pros/dani.jpeg',
        type: 'celeb',
        dataIndex: 11,
      },
      {
        firstName: 'Jenna',
        lastName: 'Johnson',
        image: '/pros/dani.jpeg',
        type: 'pro',
        dataIndex: 8,
      },
    ],
    dances: [],
    styles: shuffleStyles().slice(),
  },
  {
    id: 13,
    placement: 13,
    teamMembers: [
      {
        firstName: 'Jamie Lynn',
        lastName: 'Spears',
        image: '/pros/dani.jpeg',
        type: 'celeb',
        dataIndex: 12,
      },
      {
        firstName: 'Alan',
        lastName: 'Bersten',
        image: '/pros/dani.jpeg',
        type: 'pro',
        dataIndex: 0,
      },
    ],
    dances: [],
    styles: shuffleStyles().slice(),
  },
  {
    id: 14,
    placement: 14,
    teamMembers: [
      {
        firstName: 'Matt',
        lastName: 'Walsh',
        image: '/pros/dani.jpeg',
        type: 'celeb',
        dataIndex: 13,
      },
      {
        firstName: 'Koko',
        lastName: 'Iwasaki',
        image: '/pros/dani.jpeg',
        type: 'pro',
        dataIndex: 9,
      },
    ],
    dances: [],
    styles: shuffleStyles().slice(),
  },
];
